export const TITLE_COLOR = '#FFF';
export const TRANSPARENT_COLOR = '#00000000';

export const RAIL_BORDER_COLOR = '#073436';
export const RAIL_BACKGROUND_COLOR = '#3094CC';
export const DISABLED_RAIL_BACKGROUND_COLOR = '#CBCBCB';

export const RAIL_FILL_BORDER_COLOR = '#3D797C';
export const RAIL_FILL_BACKGROUND_COLOR = 'rgba(0, 255, 0, 0.67)';

export const THUMB_ICON_BORDER_COLOR = '#3D797C';
export const THUMB_ICON_BACKGROUND_COLOR = '#D27030';

export const DISABLED_THUMB_ICON_BORDER_COLOR = '#3C3C3C';
export const DISABLED_THUMB_ICON_BACKGROUND_COLOR = '#D3D3D3';

export const SWIPE_SUCCESS_THRESHOLD = 70;
